# permissions for end users to edit clusteranalyses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusteranalysis-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shepard
    app.kubernetes.io/part-of: shepard
    app.kubernetes.io/managed-by: kustomize
  name: clusteranalysis-editor-role
rules:
- apiGroups:
  - local-ai.spectrocloud-labs.com
  resources:
  - clusteranalyses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - local-ai.spectrocloud-labs.com
  resources:
  - clusteranalyses/status
  verbs:
  - get
