kind: Kustomization
resources:
- ../../base
images:
- name: shepard
  newName: tylergillson/shepard
  newTag: dev
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: shepard
    spec:
      template:
        spec:
          containers:
          - name: shepard
            command: ["/bin/bash", "-c", "--"]
            args: ["while true; do sleep 30; done;"]
            imagePullPolicy: Always
            resources: null
  target:
    kind: Deployment
    name: shepard
apiVersion: kustomize.config.k8s.io/v1beta1
