kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shepard-cluster-admin-role
rules:
  - apiGroups: ["*"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]