kind: Kustomization
namespace: k8sgpt

resources:
- namespace.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- deployment.yaml

images:
- name: shepard
  newName: tylergillson/shepard
  newTag: latest
